steps:
  # The CI job will be paused for third-party PR branches. It can be resumed from the Buildkite dashboard.
  - block: "Run this CI job"
    # Buildkite uses an "account:branch" naming pattern for third-party branches.
    branches: "*:*"
  - name: "Create VM"
    command: "DISPLAY=:0 vagrant up --provider virtualbox && npm install"

  - name: "Install dependencies"
    command: "vagrant ssh -c 'cd /home/vagrant/sync; npm install'"

  - name: "Build Infusion"
    command: "vagrant ssh -c 'cd /home/vagrant/sync; grunt clean stylus modulefiles:all pathMap:all copy:all copy:necessities uglify:all concat:all compress:all'"

  - name: "Run tests"
    command: "grunt tests"

  - name: "Destroy VM"
    command: "vagrant destroy -f"
