# A block step is introduced in all pull request branches before any of the steps listed below. It 
# is configured using the Buildkite web UI and has a "Run this CI job" label. It is not included 
# in this YAML configuration to prevent it from being accidentally removed as part of a PR change.
steps:
  - name: "Create VM"
    command: "DISPLAY=:0 vagrant up --provider virtualbox && npm install"
    timeout_in_minutes: 20

  # Wait and make sure the VM was successfully created before proceeding. Otherwise the remaining steps will not run.
  - wait

  - name: "Install dependencies"
    command: "vagrant ssh -c 'cd /home/vagrant/sync; npm install'"
    timeout_in_minutes: 20

  - name: "Build Infusion"
    command: "vagrant ssh -c 'cd /home/vagrant/sync; grunt clean stylus modulefiles:all pathMap:all copy:all copy:necessities uglify:all concat:all compress:all'"
    timeout_in_minutes: 20

  - name: "Run tests"
    command: "npm run test:vagrant"
    timeout_in_minutes: 20

  - name: "Destroy VM"
    command: "vagrant destroy -f"
    timeout_in_minutes: 5
