# A block step is introduced in all pull request branches before any of the steps listed below. It 
# is configured using the Buildkite web UI and has a "Run this CI job" label. It is not included 
# in this YAML configuration to prevent it from being accidentally removed as part of a PR change.

env:
  TMP_ID: "infusion-${BUILDKITE_BUILD_ID}" # Used to identify temporary containers, volumes and images

# https://github.com/buildkite/feedback/issues/173
agent_tags: &agent_tags
  agents:
    name: "${BUILDKITE_AGENT_META_DATA_NAME?}"

steps:
  - name: "Build"
    command:
      - "docker build -t ${TMP_ID} --target builder ."
      - "docker run --rm -v ${TMP_ID}:/app ${TMP_ID} true"
    timeout_in_minutes: 15
    <<: *agent_tags

  - wait

  - name: "Code Linter"
    command:
      - "docker run --rm -ti -v ${TMP_ID}:/app -w /app inclusivedesign/node-browsers grunt lint"
    timeout_in_minutes: 1
    <<: *agent_tags

  - name: "Node Tests"
    command:
      - "docker run --rm -ti -v ${TMP_ID}:/app -w /app inclusivedesign/node-browsers npm run test:node"
    timeout_in_minutes: 5
    <<: *agent_tags

  - name: "Browser Tests"
    command:
      - "docker run --rm -ti --cap-add=SYS_ADMIN -e HEADLESS=1 -v ${TMP_ID}:/app -w /app inclusivedesign/node-browsers npm run test:browser"
    timeout_in_minutes: 15
    <<: *agent_tags

  - name: "Upload Reports"
    command:
      - "docker run --rm --name ${TMP_ID} -v ${TMP_ID}:/app -v ${PWD}:/artifacts busybox cp -R /app/reports /app/products /artifacts"
    artifact_path:
      - "artifacts/**/*"
    timeout_in_minutes: 5
    <<: *agent_tags

  - wait: ~
    continue_on_failure: true

  - name: "Cleanup"
    command:
      - "docker volume rm ${TMP_ID}"
      - "docker image rm -f ${TMP_ID}"
    timeout_in_minutes: 5
    <<: *agent_tags
