# A block step is introduced in all pull request branches before any of the steps listed below. It 
# is configured using the Buildkite web UI and has a "Run this CI job" label. It is not included 
# in this YAML configuration to prevent it from being accidentally removed as part of a PR change.

env:
  TMP_ID: "infusion-${BUILDKITE_BUILD_ID}" # Used to identify temporary containers, volumes and images
  DOCKER_LIMITS: "--cpus 2 --memory 4g"

# https://github.com/buildkite/feedback/issues/173
agent_tags: &agent_tags
  agents:
    name: "${BUILDKITE_AGENT_META_DATA_NAME?}"

steps:
  - name: "Build"
    command:
      - "docker build -t ${TMP_ID} --target builder ."
      - "docker run --rm ${DOCKER_LIMITS} -v ${TMP_ID}:/app ${TMP_ID} true"
    timeout_in_minutes: 15
    <<: *agent_tags

  - wait

  - name: "Code Linter"
    command:
      - "docker run --rm -ti ${DOCKER_LIMITS} -v ${TMP_ID}:/app -w /app inclusivedesign/node-browsers grunt lint"
    timeout_in_minutes: 1
    <<: *agent_tags

  - name: "Node Tests"
    command:
      - "docker run --rm -ti ${DOCKER_LIMITS} -v ${TMP_ID}:/app -w /app inclusivedesign/node-browsers npm run test:node"
    timeout_in_minutes: 5
    <<: *agent_tags

  - name: "Browser Tests"
    command:
      - "docker run --rm -ti ${DOCKER_LIMITS} --cap-add=SYS_ADMIN -e HEADLESS=1 -v ${TMP_ID}:/app -w /app inclusivedesign/node-browsers npm run test:browser"
    timeout_in_minutes: 15
    <<: *agent_tags

  - name: "Upload Reports"
    command:
      - "mkdir -p out"
      - "docker run --rm ${DOCKER_LIMITS} --name ${TMP_ID} -v ${TMP_ID}:/app -v ${PWD}/out:/out busybox cp -R /app/reports /app/products /out"
      - "buildkite-agent artifact upload 'out/**/*'"
      - "docker run --rm ${DOCKER_LIMITS} --name ${TMP_ID} -v ${PWD}/out:/out busybox rm -rf /out/*"
      - "rm -r out"
    timeout_in_minutes: 5
    <<: *agent_tags

  - wait: ~
    continue_on_failure: true

  - name: "Cleanup"
    command:
      - "docker volume rm ${TMP_ID}"
      - "docker image rm -f ${TMP_ID}"
    timeout_in_minutes: 5
    <<: *agent_tags
